apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: devesh24/multi-client:latest
      ports:
        - containerPort: 3000